# Use the official MySQL image as the base image
FROM mysql/mysql-server:latest

# Set environment variables for the MySQL container
ENV MYSQL_ROOT_PASSWORD=accesa2023
ENV MYSQL_DATABASE=wordpress
ENV MYSQL_USER=wordpress
ENV MYSQL_PASSWORD=accesa2023

# Expose port 3306 for the MySQL database
EXPOSE 3306
